### PR TITLE
Switch to image_processing gem

### PR DESCRIPTION
**Pull request by janko**
I extracted the functionality from Refile::MiniMagick into the new [ImageProcessing](https://github.com/janko-m/image_processing) gem. The reason for that is that is that I needed processing helpers in my personal project, but I didn't want to have Refile as a dependency. I think it's nice the have a generic library that provides high-level helpers for image processing, which can be used in every project. The goal is to have a centralized place where this is improved, instead of CarrierWave, Refile and Dragonfly each implementing their own.

@jnicklas What are your thoughts on this?

### CODE REVIEW

**Comment by janko** [comment]
I checked that all tests were passing before cleaning them up.

**Comment by nest4less-dev** [comment]
@janko-m - Think this will get merged?

**Comment by janko** [comment]
@nest4less-dev I can definitely merge it, since I applied there all open issues/PRs on this repo. I was waiting for the green light from @jnicklas, but I'm sure he's busy, so I think I can go ahead and merge this. I don't have Rubygems access to release a new version, however.

I will have to review this first, since it was a pretty long time ago 😛, I will try to merge this by the end of the week.

**Comment by janko** [comment]
@nest4less-dev Well, it wasn't exactly "by the end of the week", but this is now merged. I'm fairly certain that everything should continue to work, and I also already fixed in image_processing all of the currently reported issues, so I'll be closing those.

I don't have RubyGems rights for this gem, so unfortunately I cannot release a new version of refile-mini_magick, but I updated the README to recommend folks to pull from master.

I'm happy that now Refile and Shrine will share the same image processing functionality, yay for reusability 🎉

**Pull request merged**
